name: Create Muse Dash Release

on:
  push:
    tags:
      - 'musedash-v*' # Se activa solo con tags que empiecen con "musedash-v"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: |
          # Extrae la versión del tag (lo que viene después de 'musedash-v')
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#musedash-v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Zip Release Artifact
        run: |
          zip -r "Muse-Dash-Spanish-Translation-${{ env.VERSION }}.zip" . -x ".git/*" ".github/*"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Usa el tag completo, ej. musedash-v1.0.0
          release_name: Traducción de Muse Dash v${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            ### Traducción al español para **Muse Dash**

            **Versión de la traducción:** `${{ env.VERSION }}`

            ---

            #### Instalación
            1.  Asegúrate de tener **MelonLoader** y **XUnity AutoTranslator** instalados.
            2.  Descarga el archivo `.zip` de esta release.
            3.  Extrae su contenido directamente en la carpeta raíz del juego.
            4.  Sobrescribe cualquier archivo si se te solicita.

            Para más detalles y guías, visita el [repositorio principal](https://github.com/zeedif/UnityGamesAutoTranslatorSpanish).

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Muse-Dash-Spanish-Translation-${{ env.VERSION }}.zip
          asset_name: Muse-Dash-Spanish-Translation-${{ env.VERSION }}.zip
          asset_content_type: application/zip
