name: Create Hollowbody Release

on:
  push:
    tags:
      - 'hollowbody-v*' # Se activa solo con tags que empiecen con "hollowbody-v"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso para crear la release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version from Tag
        id: get_version
        run: |
          # Extrae la versión del tag (lo que viene después de 'hollowbody-v')
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#hollowbody-v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Zip Release Artifact
        run: |
          # Comprime el contenido de la rama actual, excluyendo carpetas de Git y GitHub
          zip -r "Hollowbody-Spanish-Translation-${{ env.VERSION }}.zip" . -x ".git/*" ".github/*"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Usa el tag completo, ej. hollowbody-v1.0.0
          release_name: Traducción de Hollowbody v${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            ### Traducción al español para **Hollowbody**

            **Versión de la traducción:** `${{ env.VERSION }}`

            ---

            #### Instalación
            1.  Asegúrate de tener **BepInEx** y **XUnity AutoTranslator** instalados.
            2.  Descarga el archivo `.zip` de esta release.
            3.  Extrae su contenido directamente en la carpeta raíz del juego.
            4.  Sobrescribe cualquier archivo si se te solicita.

            Para más detalles y guías, visita el [repositorio principal](https://github.com/zeedif/UnityGamesAutoTranslatorSpanish).

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Hollowbody-Spanish-Translation-${{ env.VERSION }}.zip
          asset_name: Hollowbody-Spanish-Translation-${{ env.VERSION }}.zip
          asset_content_type: application/zip
